package(default_visibility = ["//visibility:public"])

proto_library(
    name = "web_app_services_proto",
    srcs = ["web_app_services.proto"],
    deps = [
      "@dm_core_apis//proto/internal/common:area_info_proto",
      "@dm_core_apis//proto/api/math:vec_proto",
    ]
)